import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import "@/app/globals.css";

const ibm = IBM_Plex_Sans_Thai({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["thai"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ibm.className}>
        <div className="relative flex flex-row justify-center w-screen h-screen bg-slate-950 bg-opacity-5">
          <div className="container flex flex-col justify-center items-center gap-4 p-16">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
